<?php
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Link;
use Drupal\Core\Url;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function multifarm_registration_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Добавляем ссылку.
  $form['custom_link'] = [
    '#type' => 'markup',
    '#markup' => '<p><a href="/web/custom-registration">Регистрация</a></p>',
  ];
}
